import { ArrowUpRight, ArrowLeft, Asterisk } from "lucide-react";
import type { Metadata } from "next";
export const metadata: Metadata = {title:"Learn with Gabby | Gab Real Inc.",description:"Self-guided AI courses for nontechnical business owners. Understand your tools, build useful workflows, and keep control. Coming soon."};
export default function Learn(){
return <main className="course-page" id="top">
 <a className="skip-link" href="#course-content">Skip to courses</a>
 <header className="site-header"><a className="wordmark" href="/">gab real inc<span>®</span></a><a className="inline-link" href="/"><ArrowLeft size={17}/> Back to the studio</a></header>
 <section className="course-hero" id="course-content"><span className="eyebrow">LEARN WITH GABBY / SELF-GUIDED AI EDUCATION</span><h1>You have a business to run.<br/><em>Not every tool to learn.</em></h1><p>Learn enough to make good decisions. Build something useful. Understand what it’s doing, what it needs from you, and when to leave it alone.</p><span className="status-pill"><span/>BOTH COURSES ARE IN DEVELOPMENT · ENROLLMENT IS NOT OPEN</span></section>
 <section className="course-detail" id="foundations"><div><span className="eyebrow">01 / START HERE</span><h2>AI <em>Foundations.</em></h2><p>No more rebuilding the same prompt from memory. No more wondering what AI knows about your business, or whether that confident answer is actually right.</p><div className="price-line"><strong>$297</strong><span>PLANNED PRICE · COMING SOON</span></div><p>A practical starting point for founders, consultants, creatives, and small-business owners. No coding background required.</p></div><div className="course-deliverables"><h3>What you’re working toward</h3><ol><li><strong>Know what you’re using.</strong>Understand where AI helps, where it guesses, and how to check consequential work.</li><li><strong>Stop explaining from scratch.</strong>Create reusable business context and instructions that reflect your work and voice.</li><li><strong>Give the work a clear home.</strong>Set up a small set of useful AI roles, with defined responsibilities and boundaries.</li><li><strong>Make it part of your actual week.</strong>Test repeatable workflows for research, meeting preparation, follow-ups, or planning.</li><li><strong>Keep control of your information.</strong>Know what to share, what to protect, and what should stay outside the tools.</li></ol></div></section>
 <section className="course-detail" id="advanced"><div><span className="eyebrow">02 / CONNECT THE PIECES</span><h2>Build Your<br/><em>AI System.</em></h2><p>You already use AI. Now make the context, tools, and workflows work together without building a second business just to maintain them.</p><div className="price-line"><strong>$497</strong><span>PLANNED PRICE · COMING SOON</span></div><p>For people with Foundations-level knowledge who are ready for more connected work. Start with a real need, not a collection of agents.</p></div><div className="course-deliverables"><h3>What you’re working toward</h3><ol><li><strong>Map the work before building.</strong>Understand where information enters, moves, waits, and gets lost.</li><li><strong>Build context you can take with you.</strong>Keep durable knowledge and instructions in a documented structure you control.</li><li><strong>Connect deliberately.</strong>Decide which tools need access to what, with permissions you can review and revoke.</li><li><strong>Make handoffs visible.</strong>Define roles, approval steps, error handling, and what happens when something doesn’t work.</li><li><strong>Keep the system useful.</strong>Test it against real work, document it, and simplify anything that costs more effort than it saves.</li></ol></div></section>
 <section className="course-faq"><span className="eyebrow">BEFORE YOU PLAN YOUR NEXT STEP</span><h2 style={{marginTop:20}}>A few good questions.</h2><div className="course-questions">
 <details><summary>Do I need to be technical?</summary><p>No. Foundations is designed for capable people who run real businesses, not developers. The advanced course builds on that foundation with more involved setup and testing.</p></details>
 <details><summary>Will this work with my existing tools?</summary><p>The approach is tool-agnostic, but integrations are not interchangeable. Your email, file storage, browser, account plan, and permissions can affect what works. The courses are being designed to help you assess your setup before connecting things.</p></details>
 <details><summary>Are calls or community participation required?</summary><p>No. The planned courses are self-guided. They do not include recurring calls, a managed community, or ongoing one-to-one access to Gabby.</p></details>
 <details><summary>Are software subscriptions included?</summary><p>No software subscriptions are included in the planned course prices. Final tool requirements and potential additional costs will be clearly listed before enrollment opens.</p></details>
 <details><summary>When can I enroll?</summary><p>The courses are in development. There is no confirmed launch date or active checkout yet. Follow Gabby’s writing for updates, or return here for availability.</p></details>
 </div></section>
 <section className="course-closing"><div><Asterisk size={30}/><h2 style={{marginTop:20}}>The system should serve you.</h2><p>Not the other way around. Follow the ideas behind the courses while they’re taking shape.</p></div><a className="inline-link" href="https://growithgab.substack.com/" target="_blank" rel="noreferrer">Read Grow With Gab <ArrowUpRight size={18}/></a></section>
 <footer><a href="/">← Gab Real Inc.</a><a href="/#contact">Need a more tailored approach? Work with Gabby ↗</a><span>© 2026 GAB REAL INC.</span></footer>
</main>
}
