export const caseStudies = [
  {
    number: "01",
    label: "LACES Roster Agent",
    title: "From approved athlete to live roster page.",
    problem: "At peak volume, hundreds of athletes were joining in a month. Each one needed review, a roster page, accurate records, and a useful welcome.",
    built: "A connected workflow across Growi, Notion, Webflow, and Klaviyo. The team approves athletes and reviews pages; the agent prepares records, publishes approved pages, and supports the athlete notification.",
    result: "Athletes get a public profile and clear next steps, while the team keeps its quality checks without building each page by hand.",
    metrics: [
      { value: "~500", label: "hours returned each month" },
      { value: "~6,000", label: "hours returned annually" },
      { value: "250+", label: "athletes at peak monthly volume" },
    ],
    metricBasis: "Estimated from approximately two hours returned per athlete at documented peak monthly volume.",
    financialImpact: "6,000 recovered hours × the client’s verified loaded labor rate. Revenue created from that added capacity has not yet been isolated, so it is not presented as a result.",
  },
  {
    number: "02",
    label: "Peptide Patient Portal",
    title: "One calm home for the whole patient journey.",
    problem: "Intake forms, protocols, weekly check-ins, and progress reports lived in different places. The practitioner had to piece together each patient's story.",
    built: "A private practitioner portal that brings patient profiles, recorded progress, report previews, and protocol drafts into one review flow.",
    result: "The practitioner can follow progress, review the source information, and check protocol drafts before they are sent.",
    metrics: [
      { value: "~5", label: "hours returned per new client" },
      { value: "~10", label: "hours returned each week" },
      { value: "~520", label: "recurring hours returned annually" },
    ],
    metricBasis: "Annual estimate uses ten hours per week across 52 weeks and does not include the separate per-client savings.",
    financialImpact: "Five hours per new client plus recurring weekly time × the team’s verified loaded labor rate. Incremental revenue has not yet been isolated from other growth factors.",
  },
  {
    number: "03",
    label: "Business overview",
    title: "The numbers leaders need, all in one place.",
    problem: "Important information was spread across different tools, so reports were slow to build and hard to trust.",
    built: "A central workspace that brings the company’s data together and gives each team a clear view of its work.",
    result: "Leaders can see what is happening sooner, make decisions with confidence, and catch problems before they grow.",
    metrics: [
      { value: "4", label: "disconnected platforms unified" },
      { value: "230+", label: "clients visible in one system" },
      { value: "1", label: "shared operating view" },
    ],
    metricBasis: "Scale metrics are documented. A reliable before-and-after reporting-time baseline is still being established.",
    financialImpact: "The system protects decision speed and removes repeated reporting work. A dollar value will be added only after the time baseline and revenue attribution are verified.",
  },
];
