export type Testimonial = {
  id: string;
  name: string;
  title: string;
  service: string;
  quote: string;
};

export const allTestimonialFallback: Testimonial[] = [
  { id: "emily-k", name: "Emily K", title: "Head of Client Success, Service-Based Business", service: "", quote: "Our entire team loves working with Gabby! Her patience, clear explanations during the deep-dive sessions and help resources gave our team confidence to manage everything on their own. We’re now self-sufficient, although we know Gabby’s always just an email away for ongoing support. Sometimes we are excited to find updates, so we can hop on a call and catch some of her good vibes ;)" },
  { id: "grace-r", name: "Grace R", title: "Owner & Spiritual Coach, Acupuncture & Wellness Practice", service: "Brand Kit, Website, Full CRM Implementation", quote: "Working with Gabby to up-level my acupuncture and coaching businesses has been a game changer. What felt incredibly daunting before - redoing my website and adding multiple systems automations and integrated payment software - Gabby handled everything with such ease. Any question I had during the rebuild process, Gabby had the answer. I’m truly blown away with how creative and intelligent she is, and I have felt deeply supported every step of the way. Entrusting your business and branding to someone is a deeply personal choice, and I would highly recommend Gabby to anyone who wants to know that their business is in good hands with a very trustworthy expert. Gabby adds a personal touch and so much care to something that can feel really overwhelming. Thank you Gabby!!!" },
  { id: "david-r", name: "David R", title: "Founder, AI Analytics Company", service: "", quote: "Our custom AI agents were a revelation thanks to Gabby. She built, tested, and refined bots that scrape, qualify, and nurture leads across email and social channels which is now saving us atleast 15 hours per week, plus we no longer need a team member or even full time employee to do this tedious work. Her technical expertise combined with her business acumen created a tool we aren't sure how we got by without before." },
  { id: "lisa-d", name: "Lisa D", title: "COO, Startup", service: "", quote: "What impressed me most was Gabby’s speed and clarity. She turned around a full brand refresh, web redesign, and CRM build in under six weeks, with zero sacrificing to quality. Her project plans were crystal clear, milestones were always met, and communication was top-notch. Thanks for your help, Gabby!" },
  { id: "sarah-l", name: "Sarah L", title: "Director of Operations, Service-Based Business", service: "", quote: "Implementing new systems is always overwhelming, but Gabby made it so smooth and simple. She mapped our complex sales process into the system, imported years of data flawlessly, and trained our entire operations team. Now we have real-time visibility into every prospect and our follow-up rates have skyrocketed. Working with someone who not only knows what they are doing, but is also genuinely kind and supportive really makes all the difference." },
  { id: "michael-t", name: "Michael T", title: "CEO, HealthTech Startup", service: "", quote: "Highly professional and efficient. Gabby guided us through a complete business strategy overhaul and sure does have the organization and project management dialed in. It was easy to follow along on progress the entire time. She distilled our vision into clear goals, designed a roadmap for growth, and coached our leadership team on execution once she was done building everything out. Thanks to her insight, we doubled our qualified pipeline in three months and her ongoing consulting continues to sharpen our focus." },
  { id: "james-w", name: "James W", title: "Co-Founder, eCommerce Brand", service: "", quote: "Gabby’s optimization work unlocked efficiencies we didn’t know existed. She audited our workflows, consolidated tools, and automated manual tasks. Our employees can now accomplish so much more with less stress and higher productivity! Within weeks, our order-processing time dropped by 40% and customer satisfaction improved." },
  { id: "aissia-c", name: "Aissia C", title: "Founder & Registered Nurse, Wellness & Beauty Practice", service: "Website", quote: "I consider myself so fortunate to have meet Gabby at a time where I was just embarking on getting my wellness business started. Gabby’s energetic and warm personality made the first event we collaborated together in so fun and successful! From there, I hired her to build my website and she completely nailed the most amazing website with her intellect and creativity! Gabby was professional, responsive, and showed genuine passion in creating my website to boost the growth of my business. Her visibility and execution in all she is a part of is completely seamless! I highly recommend her to all my friends that could use her exceptional service." },
  { id: "kevin-p", name: "Kevin P", title: "Marketing Director, Service-Based Business", service: "", quote: "Gabby’s personal touch sets her apart. She took the time to understand our culture, wrote on-brand copy, and iterated until every page felt right. Even after launch, she checked in regularly, suggested tweaks, and ensured our site and automations continued to perform brilliantly. Her care goes beyond just the project and we know any time we need someone to help optimize, she's the one to call!" },
  { id: "olivia-m", name: "Olivia M", title: "Founder & Wellness Coach, Wellness Coaching Business", service: "", quote: "I had multiple systems (website, booking, payments) that didn’t talk to each other. Gabby integrated everything we needed from GoHighLevel, to Stripe and our calendars. She also built us an AI sales coach that can monitor our calls and tell us where to improve, can you believe that's a real thing? My clients now have a flawless experience from discovery call to payment. It’s like she built a magic backstage conveyor belt that handles every detail." },
  { id: "rachel-h", name: "Rachel H", title: "Executive, Nonprofit Organization", service: "", quote: "Entrusting my organization’s digital transformation to Gabby was the best decision I made. She expertly guided us through branding, web design, strategic planning, AI-powered outreach, and staff training. Today, we’re reaching more donors, processing gifts faster, and scaling our impact all thanks to her partnership." },
  { id: "anna-s", name: "Anna S", title: "Founder & Creative Director, Creative Agency", service: "", quote: "From brand discovery to the final website launch, Gabby’s expertise transformed our identity. Her eye for design and strategic thinking gave us a fresh logo, a seamless site, and a narrative that perfectly captures our mission. Working with her felt like a true partnership. She always went the extra mile to make sure our brand resonated with our audience" },
  { id: "katie-k", name: "Katie K", title: "Independent Consultant, Retail", service: "", quote: "She is a true unicorn of a human in all of he ways…..and among the bevy of things she is incredible at, she is a TRUE MAVEN at all things AI. What I find most incredible about her perspective and insight on AI is how effortlessly she makes it make sense. She is able to immediately demystify things that otherwise feel intimidating, confusing of overwhelming to those of us (aka: me) who feel like dinosaurs learning about a whole new world of technology. At times, I feel like she is singlehandedly coaching me through a journey of how to function more efficiently and strategically with the help of these insane new tools that we have at our fingertips." },
  { id: "jeff-c-vision", name: "Jeff C", title: "Founder & CEO, eCommerce Brand", service: "", quote: "Gabby brought both reliable execution and real strategic vision to LACES. She consistently stayed on top of our email program, found ways to automate the work, and helped us think more deeply about how AI could support the business.\n\nWhat stood out most was her patience and adaptability. Even when we changed direction at the last minute, she understood the bigger goal and helped us make the better decision. Gabby does not just complete the work in front of her. She sees what the business could become and puts real thought into building toward that vision." },
  { id: "jeff-c-systems", name: "Jeff C", title: "Founder & CEO, eCommerce Brand", service: "", quote: "Gabby brings a rare combination of follow-through, patience, and big-picture thinking. She stays on top of execution, turns repetitive work into systems, and sees how AI can support the larger vision of the business. Even when priorities change, she remains thoughtful, adaptable, and focused on making the right decision." },
  { id: "jeff-c-execution", name: "Jeff C", title: "Founder & CEO, eCommerce Brand", service: "", quote: "Gabby does not just execute. She stays ahead of the details, turns repetitive work into systems, and keeps the long-term vision of the business in view." },
  { id: "jeff-c-ai", name: "Jeff C", title: "Founder & CEO, eCommerce Brand", service: "AI Strategy & Workflow Automation", quote: "Gabby’s technical recommendation are always incredibly helpful. She saves our team from having to research, trial and error, and spend time doing things manually. She gave us a much more scalable way to handle engagement and new inquiries." },
  { id: "natalie-g", name: "Natalie G", title: "Community Manager, eCommerce Brand", service: "AI-Powered Content Systems & Team Enablement", quote: "Gabby showed us how to use AI-guided questionnaires to make content creation and posting much easier. She does not just introduce new tools. She turns them into practical systems the team can actually use." },
  { id: "chance-s", name: "Chance S", title: "Creative Director & Content Creator, eCommerce Brand", service: "Creative Strategy, Campaign Systems & Operational Planning", quote: "The campaign planning system Gabby pulled together was incredible. It gave our team a clear way to align on the story, messaging, deliverables, metrics, and next steps so we could move faster and make decisions together." },
  { id: "sarah-c", name: "Sarah C", title: "Team Member, eCommerce Brand", service: "AI Education, Speaking & Technology", quote: "Gabby makes AI feel engaging, approachable, and relevant to real people." },
  { id: "jeff-c-advisory", name: "Jeff C", title: "Founder & CEO, eCommerce Brand", service: "Fractional Strategy & Embedded AI Advisory", quote: "Gabby has done so much for us. She became part of the day-to-day team, learned the business deeply, and invested in the work as if she were building alongside us." },
  { id: "betsy-m-session", name: "Betsy M", title: "CEO & Principal, Consulting Firm", service: "AI Education, Workshops & Speaking", quote: "Thank you again for such an amazing session! Your presentation blew me away, and I would love to engage you to help me, my family, and my small business." },
  { id: "betsy-m-tools", name: "Betsy M", title: "CEO & Principal, Consulting Firm", service: "Intelligent Interfaces, Operating Systems & Team Enablement", quote: "The tools Gabby is helping me set up will be perfect for handing work off to my growing team. She is helping me build a business that feels more organized, calm, and scalable." },
  { id: "betsy-m-coaching", name: "Betsy M", title: "CEO & Principal, Consulting Firm", service: "Strategic Advisory & Coaching", quote: "I love how Gabby is such a good coach. She helped me see that an overwhelming moment was also a sign of business growth, then gave me a clear and supportive next step." },
  { id: "brandi-c", name: "Brandi C", title: "Director of Operations, Business Coaching Company", service: "Creative Strategy, AI & Systems Advisory", quote: "Gabby and I speak the same language. She understands how I think, and our sessions quickly became one of my favorite meetings of the week. She can take a big, messy idea about AI or operations and help turn it into something practical." },
  { id: "chrissy-s", name: "Chrissy S", title: "VP of Operations, Business Coaching Company", service: "Strategic Advisory, Systems Thinking & Team Enablement", quote: "Gabby’s value goes far beyond execution. She steps into the business, observes how the team is actually working, asks the right questions, and helps uncover the gaps and opportunities that create real momentum." },
];

export const approvedTestimonialFallback = allTestimonialFallback.filter((testimonial) => testimonial.id === "katie-k");
